[Tue Jun 24 00:11:59.675184 2014] [:error] [pid 31800] [remote 187.151.44.200:37155] mod_wsgi (pid=31800): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:11:59.675321 2014] [:error] [pid 31800] [remote 187.151.44.200:37155] Traceback (most recent call last):
[Tue Jun 24 00:11:59.675347 2014] [:error] [pid 31800] [remote 187.151.44.200:37155]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:11:59.689704 2014] [:error] [pid 31800] [remote 187.151.44.200:37155]     self.load_middleware()
[Tue Jun 24 00:11:59.689728 2014] [:error] [pid 31800] [remote 187.151.44.200:37155]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:11:59.690335 2014] [:error] [pid 31800] [remote 187.151.44.200:37155]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:11:59.690356 2014] [:error] [pid 31800] [remote 187.151.44.200:37155]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:11:59.699337 2014] [:error] [pid 31800] [remote 187.151.44.200:37155]     self._setup(name)
[Tue Jun 24 00:11:59.699374 2014] [:error] [pid 31800] [remote 187.151.44.200:37155]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:11:59.699423 2014] [:error] [pid 31800] [remote 187.151.44.200:37155]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:11:59.699450 2014] [:error] [pid 31800] [remote 187.151.44.200:37155]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:11:59.699491 2014] [:error] [pid 31800] [remote 187.151.44.200:37155]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:11:59.699534 2014] [:error] [pid 31800] [remote 187.151.44.200:37155] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:12:00.458609 2014] [:error] [pid 31799] [remote 187.151.44.200:37155] mod_wsgi (pid=31799): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:12:00.458680 2014] [:error] [pid 31799] [remote 187.151.44.200:37155] Traceback (most recent call last):
[Tue Jun 24 00:12:00.458708 2014] [:error] [pid 31799] [remote 187.151.44.200:37155]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:12:00.458850 2014] [:error] [pid 31799] [remote 187.151.44.200:37155]     self.load_middleware()
[Tue Jun 24 00:12:00.458869 2014] [:error] [pid 31799] [remote 187.151.44.200:37155]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:12:00.459027 2014] [:error] [pid 31799] [remote 187.151.44.200:37155]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:12:00.459047 2014] [:error] [pid 31799] [remote 187.151.44.200:37155]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:12:00.459157 2014] [:error] [pid 31799] [remote 187.151.44.200:37155]     self._setup(name)
[Tue Jun 24 00:12:00.459174 2014] [:error] [pid 31799] [remote 187.151.44.200:37155]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:12:00.459199 2014] [:error] [pid 31799] [remote 187.151.44.200:37155]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:12:00.459212 2014] [:error] [pid 31799] [remote 187.151.44.200:37155]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:12:00.459231 2014] [:error] [pid 31799] [remote 187.151.44.200:37155]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:12:00.459254 2014] [:error] [pid 31799] [remote 187.151.44.200:37155] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:12:00.766731 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] mod_wsgi (pid=31800): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:12:00.766785 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] Traceback (most recent call last):
[Tue Jun 24 00:12:00.766818 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:12:00.766913 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self.load_middleware()
[Tue Jun 24 00:12:00.766968 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:12:00.767029 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:12:00.767155 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:12:00.767182 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self._setup(name)
[Tue Jun 24 00:12:00.767204 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:12:00.767390 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:12:00.767445 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:12:00.767481 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:12:00.767601 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:15:06.274965 2014] [:error] [pid 31799] [remote 187.151.44.200:6669] mod_wsgi (pid=31799): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:15:06.275038 2014] [:error] [pid 31799] [remote 187.151.44.200:6669] Traceback (most recent call last):
[Tue Jun 24 00:15:06.275073 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:15:06.275131 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]     self.load_middleware()
[Tue Jun 24 00:15:06.275150 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:15:06.275175 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:15:06.275189 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:15:06.275210 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]     self._setup(name)
[Tue Jun 24 00:15:06.275223 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:15:06.275243 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:15:06.275255 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:15:06.275275 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:15:06.275302 2014] [:error] [pid 31799] [remote 187.151.44.200:6669] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:15:06.778366 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] mod_wsgi (pid=31800): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:15:06.778461 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] Traceback (most recent call last):
[Tue Jun 24 00:15:06.778499 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:15:06.778553 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self.load_middleware()
[Tue Jun 24 00:15:06.778572 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:15:06.778602 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:15:06.778620 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:15:06.778650 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self._setup(name)
[Tue Jun 24 00:15:06.778667 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:15:06.778695 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:15:06.778712 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:15:06.778740 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:15:06.778774 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:15:07.078331 2014] [:error] [pid 31800] [remote 187.151.44.200:30243] mod_wsgi (pid=31800): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:15:07.078397 2014] [:error] [pid 31800] [remote 187.151.44.200:30243] Traceback (most recent call last):
[Tue Jun 24 00:15:07.078434 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:15:07.078487 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     self.load_middleware()
[Tue Jun 24 00:15:07.078508 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:15:07.078541 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:15:07.078560 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:15:07.078592 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     self._setup(name)
[Tue Jun 24 00:15:07.078610 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:15:07.078640 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:15:07.078658 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:15:07.078688 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:15:07.078723 2014] [:error] [pid 31800] [remote 187.151.44.200:30243] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:15:20.238540 2014] [:error] [pid 31800] [remote 187.151.44.200:30243] mod_wsgi (pid=31800): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:15:20.238761 2014] [:error] [pid 31800] [remote 187.151.44.200:30243] Traceback (most recent call last):
[Tue Jun 24 00:15:20.238795 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:15:20.238837 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     self.load_middleware()
[Tue Jun 24 00:15:20.238851 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:15:20.239029 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:15:20.239134 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:15:20.239169 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     self._setup(name)
[Tue Jun 24 00:15:20.239184 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:15:20.239284 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:15:20.239361 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:15:20.239447 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:15:20.239478 2014] [:error] [pid 31800] [remote 187.151.44.200:30243] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:15:20.671258 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] mod_wsgi (pid=31800): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:15:20.671334 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] Traceback (most recent call last):
[Tue Jun 24 00:15:20.671375 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:15:20.671436 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self.load_middleware()
[Tue Jun 24 00:15:20.671465 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:15:20.671515 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:15:20.671542 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:15:20.671591 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self._setup(name)
[Tue Jun 24 00:15:20.671621 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:15:20.671667 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:15:20.671698 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:15:20.671737 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:15:20.671768 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:15:20.968438 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] mod_wsgi (pid=31800): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:15:20.968501 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] Traceback (most recent call last):
[Tue Jun 24 00:15:20.968537 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:15:20.968639 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self.load_middleware()
[Tue Jun 24 00:15:20.968666 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:15:20.968696 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:15:20.968713 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:15:20.968747 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self._setup(name)
[Tue Jun 24 00:15:20.968769 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:15:20.968876 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:15:20.968906 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:15:20.968944 2014] [:error] [pid 31800] [remote 187.151.44.200:6669]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:15:20.968982 2014] [:error] [pid 31800] [remote 187.151.44.200:6669] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:15:35.145885 2014] [:error] [pid 31800] [remote 187.151.44.200:30243] mod_wsgi (pid=31800): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:15:35.145943 2014] [:error] [pid 31800] [remote 187.151.44.200:30243] Traceback (most recent call last):
[Tue Jun 24 00:15:35.146048 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:15:35.146096 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     self.load_middleware()
[Tue Jun 24 00:15:35.146113 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:15:35.146141 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:15:35.146155 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:15:35.146175 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     self._setup(name)
[Tue Jun 24 00:15:35.146188 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:15:35.146207 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:15:35.146219 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:15:35.146239 2014] [:error] [pid 31800] [remote 187.151.44.200:30243]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:15:35.146264 2014] [:error] [pid 31800] [remote 187.151.44.200:30243] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:15:35.639670 2014] [:error] [pid 31799] [remote 187.151.44.200:6669] mod_wsgi (pid=31799): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:15:35.639722 2014] [:error] [pid 31799] [remote 187.151.44.200:6669] Traceback (most recent call last):
[Tue Jun 24 00:15:35.639751 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:15:35.639792 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]     self.load_middleware()
[Tue Jun 24 00:15:35.639806 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:15:35.639828 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:15:35.639962 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:15:35.639996 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]     self._setup(name)
[Tue Jun 24 00:15:35.640009 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:15:35.640029 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:15:35.640042 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:15:35.640061 2014] [:error] [pid 31799] [remote 187.151.44.200:6669]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:15:35.640086 2014] [:error] [pid 31799] [remote 187.151.44.200:6669] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:15:35.967350 2014] [:error] [pid 31799] [remote 187.151.44.200:30243] mod_wsgi (pid=31799): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:15:35.967404 2014] [:error] [pid 31799] [remote 187.151.44.200:30243] Traceback (most recent call last):
[Tue Jun 24 00:15:35.967433 2014] [:error] [pid 31799] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:15:35.967474 2014] [:error] [pid 31799] [remote 187.151.44.200:30243]     self.load_middleware()
[Tue Jun 24 00:15:35.967488 2014] [:error] [pid 31799] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:15:35.967510 2014] [:error] [pid 31799] [remote 187.151.44.200:30243]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:15:35.967522 2014] [:error] [pid 31799] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:15:35.967543 2014] [:error] [pid 31799] [remote 187.151.44.200:30243]     self._setup(name)
[Tue Jun 24 00:15:35.967555 2014] [:error] [pid 31799] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:15:35.967574 2014] [:error] [pid 31799] [remote 187.151.44.200:30243]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:15:35.967586 2014] [:error] [pid 31799] [remote 187.151.44.200:30243]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:15:35.967604 2014] [:error] [pid 31799] [remote 187.151.44.200:30243]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:15:35.967629 2014] [:error] [pid 31799] [remote 187.151.44.200:30243] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:23:25.586423 2014] [:error] [pid 31973] [remote 187.151.44.200:2089] mod_wsgi (pid=31973): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:23:25.586502 2014] [:error] [pid 31973] [remote 187.151.44.200:2089] Traceback (most recent call last):
[Tue Jun 24 00:23:25.586528 2014] [:error] [pid 31973] [remote 187.151.44.200:2089]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:23:25.586664 2014] [:error] [pid 31973] [remote 187.151.44.200:2089]     self.load_middleware()
[Tue Jun 24 00:23:25.586683 2014] [:error] [pid 31973] [remote 187.151.44.200:2089]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:23:25.586833 2014] [:error] [pid 31973] [remote 187.151.44.200:2089]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:23:25.586853 2014] [:error] [pid 31973] [remote 187.151.44.200:2089]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:23:25.586963 2014] [:error] [pid 31973] [remote 187.151.44.200:2089]     self._setup(name)
[Tue Jun 24 00:23:25.586982 2014] [:error] [pid 31973] [remote 187.151.44.200:2089]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:23:25.587007 2014] [:error] [pid 31973] [remote 187.151.44.200:2089]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:23:25.587020 2014] [:error] [pid 31973] [remote 187.151.44.200:2089]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:23:25.587041 2014] [:error] [pid 31973] [remote 187.151.44.200:2089]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:23:25.587065 2014] [:error] [pid 31973] [remote 187.151.44.200:2089] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:23:26.370316 2014] [:error] [pid 31972] [remote 187.151.44.200:2089] mod_wsgi (pid=31972): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:23:26.370391 2014] [:error] [pid 31972] [remote 187.151.44.200:2089] Traceback (most recent call last):
[Tue Jun 24 00:23:26.370420 2014] [:error] [pid 31972] [remote 187.151.44.200:2089]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:23:26.370564 2014] [:error] [pid 31972] [remote 187.151.44.200:2089]     self.load_middleware()
[Tue Jun 24 00:23:26.370583 2014] [:error] [pid 31972] [remote 187.151.44.200:2089]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:23:26.370736 2014] [:error] [pid 31972] [remote 187.151.44.200:2089]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:23:26.370755 2014] [:error] [pid 31972] [remote 187.151.44.200:2089]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:23:26.370865 2014] [:error] [pid 31972] [remote 187.151.44.200:2089]     self._setup(name)
[Tue Jun 24 00:23:26.370891 2014] [:error] [pid 31972] [remote 187.151.44.200:2089]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:23:26.370918 2014] [:error] [pid 31972] [remote 187.151.44.200:2089]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:23:26.370932 2014] [:error] [pid 31972] [remote 187.151.44.200:2089]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:23:26.370953 2014] [:error] [pid 31972] [remote 187.151.44.200:2089]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:23:26.370994 2014] [:error] [pid 31972] [remote 187.151.44.200:2089] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:23:26.665530 2014] [:error] [pid 31972] [remote 187.151.44.200:60712] mod_wsgi (pid=31972): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:23:26.665591 2014] [:error] [pid 31972] [remote 187.151.44.200:60712] Traceback (most recent call last):
[Tue Jun 24 00:23:26.665641 2014] [:error] [pid 31972] [remote 187.151.44.200:60712]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:23:26.665701 2014] [:error] [pid 31972] [remote 187.151.44.200:60712]     self.load_middleware()
[Tue Jun 24 00:23:26.665731 2014] [:error] [pid 31972] [remote 187.151.44.200:60712]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:23:26.665778 2014] [:error] [pid 31972] [remote 187.151.44.200:60712]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:23:26.665805 2014] [:error] [pid 31972] [remote 187.151.44.200:60712]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:23:26.665846 2014] [:error] [pid 31972] [remote 187.151.44.200:60712]     self._setup(name)
[Tue Jun 24 00:23:26.665870 2014] [:error] [pid 31972] [remote 187.151.44.200:60712]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:23:26.665910 2014] [:error] [pid 31972] [remote 187.151.44.200:60712]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:23:26.665935 2014] [:error] [pid 31972] [remote 187.151.44.200:60712]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 132, in __init__
[Tue Jun 24 00:23:26.665974 2014] [:error] [pid 31972] [remote 187.151.44.200:60712]     % (self.SETTINGS_MODULE, e)
[Tue Jun 24 00:23:26.666016 2014] [:error] [pid 31972] [remote 187.151.44.200:60712] ImportError: Could not import settings 'djalton.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named djalton.settings
[Tue Jun 24 00:43:58.573549 2014] [:error] [pid 32358] [remote 187.151.44.200:21329] mod_wsgi (pid=32358): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:43:58.573640 2014] [:error] [pid 32358] [remote 187.151.44.200:21329] Traceback (most recent call last):
[Tue Jun 24 00:43:58.573679 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]   File "/var/www/djalton/djalton/wsgi.py", line 31, in application
[Tue Jun 24 00:43:58.573775 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]     return _application(environ, start_response)
[Tue Jun 24 00:43:58.573797 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:43:58.573947 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]     self.load_middleware()
[Tue Jun 24 00:43:58.574006 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:43:58.574177 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:43:58.574198 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:43:58.574304 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]     self._setup(name)
[Tue Jun 24 00:43:58.574322 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:43:58.574346 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:43:58.574367 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
[Tue Jun 24 00:43:58.574389 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Tue Jun 24 00:43:58.574401 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
[Tue Jun 24 00:43:58.578945 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]     __import__(name)
[Tue Jun 24 00:43:58.579009 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]   File "/var/www/djalton/djalton/settings.py", line 99
[Tue Jun 24 00:43:58.579020 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]     ADMIN_MEDIA_PREFIX = '/static/admin/'
[Tue Jun 24 00:43:58.579027 2014] [:error] [pid 32358] [remote 187.151.44.200:21329]                        ^
[Tue Jun 24 00:43:58.579033 2014] [:error] [pid 32358] [remote 187.151.44.200:21329] SyntaxError: invalid syntax
[Tue Jun 24 00:43:59.057637 2014] [:error] [pid 32358] [remote 187.151.44.200:56378] mod_wsgi (pid=32358): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:43:59.058429 2014] [:error] [pid 32358] [remote 187.151.44.200:56378] Traceback (most recent call last):
[Tue Jun 24 00:43:59.058481 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]   File "/var/www/djalton/djalton/wsgi.py", line 31, in application
[Tue Jun 24 00:43:59.058837 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]     return _application(environ, start_response)
[Tue Jun 24 00:43:59.058955 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:43:59.059003 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]     self.load_middleware()
[Tue Jun 24 00:43:59.059026 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:43:59.059062 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:43:59.059089 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:43:59.059152 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]     self._setup(name)
[Tue Jun 24 00:43:59.059179 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:43:59.059218 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:43:59.059243 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
[Tue Jun 24 00:43:59.059281 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Tue Jun 24 00:43:59.059307 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
[Tue Jun 24 00:43:59.059349 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]     __import__(name)
[Tue Jun 24 00:43:59.059428 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]   File "/var/www/djalton/djalton/settings.py", line 99
[Tue Jun 24 00:43:59.059446 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]     ADMIN_MEDIA_PREFIX = '/static/admin/'
[Tue Jun 24 00:43:59.059459 2014] [:error] [pid 32358] [remote 187.151.44.200:56378]                        ^
[Tue Jun 24 00:43:59.059470 2014] [:error] [pid 32358] [remote 187.151.44.200:56378] SyntaxError: invalid syntax
[Tue Jun 24 00:43:59.648789 2014] [:error] [pid 32357] [remote 187.151.44.200:21329] mod_wsgi (pid=32357): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Tue Jun 24 00:43:59.648868 2014] [:error] [pid 32357] [remote 187.151.44.200:21329] Traceback (most recent call last):
[Tue Jun 24 00:43:59.648899 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]   File "/var/www/djalton/djalton/wsgi.py", line 31, in application
[Tue Jun 24 00:43:59.648998 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]     return _application(environ, start_response)
[Tue Jun 24 00:43:59.649030 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Tue Jun 24 00:43:59.649149 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]     self.load_middleware()
[Tue Jun 24 00:43:59.649168 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Tue Jun 24 00:43:59.649322 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Tue Jun 24 00:43:59.649341 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Tue Jun 24 00:43:59.649446 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]     self._setup(name)
[Tue Jun 24 00:43:59.649464 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Tue Jun 24 00:43:59.649488 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]     self._wrapped = Settings(settings_module)
[Tue Jun 24 00:43:59.649501 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
[Tue Jun 24 00:43:59.649521 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Tue Jun 24 00:43:59.649534 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
[Tue Jun 24 00:43:59.649591 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]     __import__(name)
[Tue Jun 24 00:43:59.649645 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]   File "/var/www/djalton/djalton/settings.py", line 99
[Tue Jun 24 00:43:59.649655 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]     ADMIN_MEDIA_PREFIX = '/static/admin/'
[Tue Jun 24 00:43:59.649662 2014] [:error] [pid 32357] [remote 187.151.44.200:21329]                        ^
[Tue Jun 24 00:43:59.649668 2014] [:error] [pid 32357] [remote 187.151.44.200:21329] SyntaxError: invalid syntax
[Tue Jun 24 05:08:00.186070 2014] [:error] [pid 32559] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Tue Jun 24 05:08:00.186126 2014] [:error] [pid 32559]   from django.utils import simplejson
[Tue Jun 24 05:08:00.186132 2014] [:error] [pid 32559] 
[Tue Jun 24 05:08:01.148856 2014] [:error] [pid 32560] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Tue Jun 24 05:08:01.148905 2014] [:error] [pid 32560]   from django.utils import simplejson
[Tue Jun 24 05:08:01.148911 2014] [:error] [pid 32560] 
[Tue Jun 24 05:20:27.363495 2014] [:error] [pid 318] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Tue Jun 24 05:20:27.363557 2014] [:error] [pid 318]   from django.utils import simplejson
[Tue Jun 24 05:20:27.363562 2014] [:error] [pid 318] 
[Tue Jun 24 05:20:28.187552 2014] [:error] [pid 319] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Tue Jun 24 05:20:28.187620 2014] [:error] [pid 319]   from django.utils import simplejson
[Tue Jun 24 05:20:28.187625 2014] [:error] [pid 319] 
[Tue Jun 24 05:26:19.847107 2014] [:error] [pid 474] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Tue Jun 24 05:26:19.847172 2014] [:error] [pid 474]   from django.utils import simplejson
[Tue Jun 24 05:26:19.847185 2014] [:error] [pid 474] 
[Tue Jun 24 05:26:20.746152 2014] [:error] [pid 473] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Tue Jun 24 05:26:20.746203 2014] [:error] [pid 473]   from django.utils import simplejson
[Tue Jun 24 05:26:20.746208 2014] [:error] [pid 473] 
[Tue Jun 24 05:28:09.893061 2014] [:error] [pid 609] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Tue Jun 24 05:28:09.893124 2014] [:error] [pid 609]   from django.utils import simplejson
[Tue Jun 24 05:28:09.893129 2014] [:error] [pid 609] 
[Tue Jun 24 05:28:11.175399 2014] [:error] [pid 608] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Tue Jun 24 05:28:11.175448 2014] [:error] [pid 608]   from django.utils import simplejson
[Tue Jun 24 05:28:11.175454 2014] [:error] [pid 608] 
[Wed Jun 25 01:31:28.365989 2014] [:error] [pid 4043] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 01:31:28.366047 2014] [:error] [pid 4043]   from django.utils import simplejson
[Wed Jun 25 01:31:28.366053 2014] [:error] [pid 4043] 
[Wed Jun 25 01:31:33.068853 2014] [:error] [pid 4042] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 01:31:33.068911 2014] [:error] [pid 4042]   from django.utils import simplejson
[Wed Jun 25 01:31:33.068917 2014] [:error] [pid 4042] 
[Wed Jun 25 01:33:09.551731 2014] [:error] [pid 4173] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 01:33:09.551790 2014] [:error] [pid 4173]   from django.utils import simplejson
[Wed Jun 25 01:33:09.551795 2014] [:error] [pid 4173] 
[Wed Jun 25 01:33:11.551043 2014] [:error] [pid 4174] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 01:33:11.551100 2014] [:error] [pid 4174]   from django.utils import simplejson
[Wed Jun 25 01:33:11.551105 2014] [:error] [pid 4174] 
[Wed Jun 25 01:35:39.747308 2014] [:error] [pid 4309] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 01:35:39.747364 2014] [:error] [pid 4309]   from django.utils import simplejson
[Wed Jun 25 01:35:39.747370 2014] [:error] [pid 4309] 
[Wed Jun 25 01:35:41.075723 2014] [:error] [pid 4310] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 01:35:41.075776 2014] [:error] [pid 4310]   from django.utils import simplejson
[Wed Jun 25 01:35:41.075781 2014] [:error] [pid 4310] 
[Wed Jun 25 02:03:11.483583 2014] [:error] [pid 4569] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 02:03:11.483640 2014] [:error] [pid 4569]   from django.utils import simplejson
[Wed Jun 25 02:03:11.483646 2014] [:error] [pid 4569] 
[Wed Jun 25 02:03:12.553526 2014] [:error] [pid 4568] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 02:03:12.553590 2014] [:error] [pid 4568]   from django.utils import simplejson
[Wed Jun 25 02:03:12.553596 2014] [:error] [pid 4568] 
[Wed Jun 25 02:46:14.575163 2014] [:error] [pid 4849] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 02:46:14.575233 2014] [:error] [pid 4849]   from django.utils import simplejson
[Wed Jun 25 02:46:14.575239 2014] [:error] [pid 4849] 
[Wed Jun 25 02:46:15.471585 2014] [:error] [pid 4848] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 02:46:15.471636 2014] [:error] [pid 4848]   from django.utils import simplejson
[Wed Jun 25 02:46:15.471641 2014] [:error] [pid 4848] 
[Wed Jun 25 02:52:49.287370 2014] [:error] [pid 5034] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 02:52:49.287437 2014] [:error] [pid 5034]   from django.utils import simplejson
[Wed Jun 25 02:52:49.287443 2014] [:error] [pid 5034] 
[Wed Jun 25 02:52:50.388604 2014] [:error] [pid 5033] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 02:52:50.388670 2014] [:error] [pid 5033]   from django.utils import simplejson
[Wed Jun 25 02:52:50.388676 2014] [:error] [pid 5033] 
[Wed Jun 25 03:23:16.081072 2014] [:error] [pid 5273] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:23:16.081129 2014] [:error] [pid 5273]   from django.utils import simplejson
[Wed Jun 25 03:23:16.081134 2014] [:error] [pid 5273] 
[Wed Jun 25 03:23:16.981402 2014] [:error] [pid 5274] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:23:16.981454 2014] [:error] [pid 5274]   from django.utils import simplejson
[Wed Jun 25 03:23:16.981460 2014] [:error] [pid 5274] 
[Wed Jun 25 03:25:36.675409 2014] [:error] [pid 5408] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:25:36.675466 2014] [:error] [pid 5408]   from django.utils import simplejson
[Wed Jun 25 03:25:36.675472 2014] [:error] [pid 5408] 
[Wed Jun 25 03:25:38.261442 2014] [:error] [pid 5409] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:25:38.261496 2014] [:error] [pid 5409]   from django.utils import simplejson
[Wed Jun 25 03:25:38.261501 2014] [:error] [pid 5409] 
[Wed Jun 25 03:28:03.355612 2014] [:error] [pid 5545] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:28:03.355669 2014] [:error] [pid 5545]   from django.utils import simplejson
[Wed Jun 25 03:28:03.355675 2014] [:error] [pid 5545] 
[Wed Jun 25 03:28:04.366452 2014] [:error] [pid 5544] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:28:04.366503 2014] [:error] [pid 5544]   from django.utils import simplejson
[Wed Jun 25 03:28:04.366508 2014] [:error] [pid 5544] 
[Wed Jun 25 03:28:45.377915 2014] [:error] [pid 5679] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:28:45.377981 2014] [:error] [pid 5679]   from django.utils import simplejson
[Wed Jun 25 03:28:45.377986 2014] [:error] [pid 5679] 
[Wed Jun 25 03:28:46.262605 2014] [:error] [pid 5678] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:28:46.262677 2014] [:error] [pid 5678]   from django.utils import simplejson
[Wed Jun 25 03:28:46.262682 2014] [:error] [pid 5678] 
[Wed Jun 25 03:31:48.882292 2014] [:error] [pid 5814] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:31:48.882355 2014] [:error] [pid 5814]   from django.utils import simplejson
[Wed Jun 25 03:31:48.882360 2014] [:error] [pid 5814] 
[Wed Jun 25 03:31:50.076395 2014] [:error] [pid 5815] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:31:50.076458 2014] [:error] [pid 5815]   from django.utils import simplejson
[Wed Jun 25 03:31:50.076463 2014] [:error] [pid 5815] 
[Wed Jun 25 03:35:10.783403 2014] [:error] [pid 5956] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:35:10.783465 2014] [:error] [pid 5956]   from django.utils import simplejson
[Wed Jun 25 03:35:10.783471 2014] [:error] [pid 5956] 
[Wed Jun 25 03:35:11.964377 2014] [:error] [pid 5955] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:35:11.964428 2014] [:error] [pid 5955]   from django.utils import simplejson
[Wed Jun 25 03:35:11.964434 2014] [:error] [pid 5955] 
[Wed Jun 25 03:39:29.651158 2014] [:error] [pid 6101] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:39:29.651227 2014] [:error] [pid 6101]   from django.utils import simplejson
[Wed Jun 25 03:39:29.651233 2014] [:error] [pid 6101] 
[Wed Jun 25 03:40:17.694803 2014] [:error] [pid 6247] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:40:17.694865 2014] [:error] [pid 6247]   from django.utils import simplejson
[Wed Jun 25 03:40:17.694871 2014] [:error] [pid 6247] 
[Wed Jun 25 03:40:18.975654 2014] [:error] [pid 6246] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:40:18.975716 2014] [:error] [pid 6246]   from django.utils import simplejson
[Wed Jun 25 03:40:18.975721 2014] [:error] [pid 6246] 
[Wed Jun 25 03:42:28.686290 2014] [:error] [pid 6382] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:42:28.686356 2014] [:error] [pid 6382]   from django.utils import simplejson
[Wed Jun 25 03:42:28.686362 2014] [:error] [pid 6382] 
[Wed Jun 25 03:42:29.969870 2014] [:error] [pid 6381] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:42:29.969925 2014] [:error] [pid 6381]   from django.utils import simplejson
[Wed Jun 25 03:42:29.969930 2014] [:error] [pid 6381] 
[Wed Jun 25 03:43:39.778720 2014] [:error] [pid 6516] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:43:39.778783 2014] [:error] [pid 6516]   from django.utils import simplejson
[Wed Jun 25 03:43:39.778789 2014] [:error] [pid 6516] 
[Wed Jun 25 03:43:40.679758 2014] [:error] [pid 6515] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:43:40.679812 2014] [:error] [pid 6515]   from django.utils import simplejson
[Wed Jun 25 03:43:40.679818 2014] [:error] [pid 6515] 
[Wed Jun 25 03:50:40.450799 2014] [:error] [pid 6650] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:50:40.450880 2014] [:error] [pid 6650]   from django.utils import simplejson
[Wed Jun 25 03:50:40.450891 2014] [:error] [pid 6650] 
[Wed Jun 25 03:50:41.561790 2014] [:error] [pid 6649] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:50:41.561847 2014] [:error] [pid 6649]   from django.utils import simplejson
[Wed Jun 25 03:50:41.561852 2014] [:error] [pid 6649] 
[Wed Jun 25 03:52:07.260509 2014] [:error] [pid 6785] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:52:07.260562 2014] [:error] [pid 6785]   from django.utils import simplejson
[Wed Jun 25 03:52:07.260567 2014] [:error] [pid 6785] 
[Wed Jun 25 03:52:08.450806 2014] [:error] [pid 6784] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:52:08.450866 2014] [:error] [pid 6784]   from django.utils import simplejson
[Wed Jun 25 03:52:08.450877 2014] [:error] [pid 6784] 
[Wed Jun 25 03:56:28.261585 2014] [:error] [pid 6920] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:56:28.261650 2014] [:error] [pid 6920]   from django.utils import simplejson
[Wed Jun 25 03:56:28.261656 2014] [:error] [pid 6920] 
[Wed Jun 25 03:56:30.045469 2014] [:error] [pid 6919] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:56:30.045533 2014] [:error] [pid 6919]   from django.utils import simplejson
[Wed Jun 25 03:56:30.045543 2014] [:error] [pid 6919] 
[Wed Jun 25 03:59:21.972713 2014] [:error] [pid 7054] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:59:21.972782 2014] [:error] [pid 7054]   from django.utils import simplejson
[Wed Jun 25 03:59:21.972787 2014] [:error] [pid 7054] 
[Wed Jun 25 03:59:22.984050 2014] [:error] [pid 7053] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 03:59:22.984108 2014] [:error] [pid 7053]   from django.utils import simplejson
[Wed Jun 25 03:59:22.984114 2014] [:error] [pid 7053] 
[Wed Jun 25 04:03:41.174514 2014] [:error] [pid 7189] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 04:03:41.174569 2014] [:error] [pid 7189]   from django.utils import simplejson
[Wed Jun 25 04:03:41.174575 2014] [:error] [pid 7189] 
[Wed Jun 25 04:03:42.346146 2014] [:error] [pid 7188] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Wed Jun 25 04:03:42.346198 2014] [:error] [pid 7188]   from django.utils import simplejson
[Wed Jun 25 04:03:42.346204 2014] [:error] [pid 7188] 
[Fri Jun 27 03:15:33.970864 2014] [:error] [pid 17131] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 03:15:33.970938 2014] [:error] [pid 17131]   from django.utils import simplejson
[Fri Jun 27 03:15:33.970956 2014] [:error] [pid 17131] 
[Fri Jun 27 03:15:35.149976 2014] [:error] [pid 17130] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 03:15:35.150111 2014] [:error] [pid 17130]   from django.utils import simplejson
[Fri Jun 27 03:15:35.150118 2014] [:error] [pid 17130] 
[Fri Jun 27 03:19:15.592766 2014] [:error] [pid 17269] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 03:19:15.592838 2014] [:error] [pid 17269]   from django.utils import simplejson
[Fri Jun 27 03:19:15.592849 2014] [:error] [pid 17269] 
[Fri Jun 27 03:19:16.874575 2014] [:error] [pid 17270] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 03:19:16.874627 2014] [:error] [pid 17270]   from django.utils import simplejson
[Fri Jun 27 03:19:16.874632 2014] [:error] [pid 17270] 
[Fri Jun 27 03:27:22.989270 2014] [:error] [pid 17531] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 03:27:22.989318 2014] [:error] [pid 17531]   from django.utils import simplejson
[Fri Jun 27 03:27:22.989323 2014] [:error] [pid 17531] 
[Fri Jun 27 03:33:02.193343 2014] [:error] [pid 17530] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 03:33:02.193393 2014] [:error] [pid 17530]   from django.utils import simplejson
[Fri Jun 27 03:33:02.193399 2014] [:error] [pid 17530] 
[Fri Jun 27 03:36:15.571519 2014] [:error] [pid 17666] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 03:36:15.571572 2014] [:error] [pid 17666]   from django.utils import simplejson
[Fri Jun 27 03:36:15.571578 2014] [:error] [pid 17666] 
[Fri Jun 27 03:36:18.773737 2014] [:error] [pid 17665] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 03:36:18.773782 2014] [:error] [pid 17665]   from django.utils import simplejson
[Fri Jun 27 03:36:18.773787 2014] [:error] [pid 17665] 
[Fri Jun 27 03:55:22.669733 2014] [:error] [pid 17842] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 03:55:22.669790 2014] [:error] [pid 17842]   from django.utils import simplejson
[Fri Jun 27 03:55:22.669796 2014] [:error] [pid 17842] 
[Fri Jun 27 03:57:06.775766 2014] [:error] [pid 17976] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 03:57:06.775827 2014] [:error] [pid 17976]   from django.utils import simplejson
[Fri Jun 27 03:57:06.775832 2014] [:error] [pid 17976] 
[Fri Jun 27 03:59:37.166818 2014] [:error] [pid 18110] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 03:59:37.166865 2014] [:error] [pid 18110]   from django.utils import simplejson
[Fri Jun 27 03:59:37.166870 2014] [:error] [pid 18110] 
[Fri Jun 27 04:00:25.467826 2014] [:error] [pid 18262] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:00:25.467873 2014] [:error] [pid 18262]   from django.utils import simplejson
[Fri Jun 27 04:00:25.467879 2014] [:error] [pid 18262] 
[Fri Jun 27 04:00:28.576684 2014] [:error] [pid 18261] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:00:28.576727 2014] [:error] [pid 18261]   from django.utils import simplejson
[Fri Jun 27 04:00:28.576733 2014] [:error] [pid 18261] 
[Fri Jun 27 00:02:12.130257 2014] [:error] [pid 18336] (2)No such file or directory: [client 187.151.20.205:50973] mod_wsgi (pid=18336): Unable to connect to WSGI daemon process 'djalton.djangoserver' on '/var/run/apache2/wsgi.11528.27.1.sock' after multiple attempts., referer: http://dalton.jualjiman.com/portafolio/
[Fri Jun 27 04:02:13.071929 2014] [:error] [pid 18402] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:02:13.071988 2014] [:error] [pid 18402]   from django.utils import simplejson
[Fri Jun 27 04:02:13.071993 2014] [:error] [pid 18402] 
[Fri Jun 27 04:02:16.281071 2014] [:error] [pid 18401] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:02:16.281133 2014] [:error] [pid 18401]   from django.utils import simplejson
[Fri Jun 27 04:02:16.281142 2014] [:error] [pid 18401] 
[Fri Jun 27 04:05:23.960024 2014] [:error] [pid 18542] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:05:23.960086 2014] [:error] [pid 18542]   from django.utils import simplejson
[Fri Jun 27 04:05:23.960096 2014] [:error] [pid 18542] 
[Fri Jun 27 04:05:25.266272 2014] [:error] [pid 18543] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:05:25.266318 2014] [:error] [pid 18543]   from django.utils import simplejson
[Fri Jun 27 04:05:25.266323 2014] [:error] [pid 18543] 
[Fri Jun 27 04:08:18.494039 2014] [:error] [pid 18701] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:08:18.543952 2014] [:error] [pid 18701]   from django.utils import simplejson
[Fri Jun 27 04:08:18.543991 2014] [:error] [pid 18701] 
[Fri Jun 27 04:08:19.453840 2014] [:error] [pid 18700] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:08:19.453885 2014] [:error] [pid 18700]   from django.utils import simplejson
[Fri Jun 27 04:08:19.453890 2014] [:error] [pid 18700] 
[Fri Jun 27 04:19:09.482709 2014] [:error] [pid 18854] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:19:09.482758 2014] [:error] [pid 18854]   from django.utils import simplejson
[Fri Jun 27 04:19:09.482764 2014] [:error] [pid 18854] 
[Fri Jun 27 04:20:44.283998 2014] [:error] [pid 19006] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:20:44.284049 2014] [:error] [pid 19006]   from django.utils import simplejson
[Fri Jun 27 04:20:44.284088 2014] [:error] [pid 19006] 
[Fri Jun 27 04:20:45.369976 2014] [:error] [pid 19005] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:20:45.370020 2014] [:error] [pid 19005]   from django.utils import simplejson
[Fri Jun 27 04:20:45.370026 2014] [:error] [pid 19005] 
[Fri Jun 27 04:23:00.993179 2014] [:error] [pid 19146] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:23:00.993231 2014] [:error] [pid 19146]   from django.utils import simplejson
[Fri Jun 27 04:23:00.993237 2014] [:error] [pid 19146] 
[Fri Jun 27 04:23:03.657417 2014] [:error] [pid 19145] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jun 27 04:23:03.657463 2014] [:error] [pid 19145]   from django.utils import simplejson
[Fri Jun 27 04:23:03.657469 2014] [:error] [pid 19145] 
[Sat Jun 28 04:38:39.823870 2014] [:error] [pid 21398] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 04:38:39.823932 2014] [:error] [pid 21398]   from django.utils import simplejson
[Sat Jun 28 04:38:39.823938 2014] [:error] [pid 21398] 
[Sat Jun 28 04:40:18.168420 2014] [:error] [pid 21561] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 04:40:18.168478 2014] [:error] [pid 21561]   from django.utils import simplejson
[Sat Jun 28 04:40:18.168483 2014] [:error] [pid 21561] 
[Sat Jun 28 04:40:19.766508 2014] [:error] [pid 21560] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 04:40:19.766552 2014] [:error] [pid 21560]   from django.utils import simplejson
[Sat Jun 28 04:40:19.766557 2014] [:error] [pid 21560] 
[Sat Jun 28 04:45:39.749383 2014] [:error] [pid 21702] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 04:45:39.749435 2014] [:error] [pid 21702]   from django.utils import simplejson
[Sat Jun 28 04:45:39.749440 2014] [:error] [pid 21702] 
[Sat Jun 28 04:45:42.344235 2014] [:error] [pid 21703] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 04:45:42.344289 2014] [:error] [pid 21703]   from django.utils import simplejson
[Sat Jun 28 04:45:42.344294 2014] [:error] [pid 21703] 
[Sat Jun 28 04:46:33.374997 2014] [:error] [pid 21837] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 04:46:33.375048 2014] [:error] [pid 21837]   from django.utils import simplejson
[Sat Jun 28 04:46:33.375054 2014] [:error] [pid 21837] 
[Sat Jun 28 04:46:34.558211 2014] [:error] [pid 21836] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 04:46:34.558253 2014] [:error] [pid 21836]   from django.utils import simplejson
[Sat Jun 28 04:46:34.558259 2014] [:error] [pid 21836] 
[Sat Jun 28 04:49:41.285261 2014] [:error] [pid 21976] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 04:49:41.285310 2014] [:error] [pid 21976]   from django.utils import simplejson
[Sat Jun 28 04:49:41.285315 2014] [:error] [pid 21976] 
[Sat Jun 28 04:49:42.652611 2014] [:error] [pid 21975] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 04:49:42.652656 2014] [:error] [pid 21975]   from django.utils import simplejson
[Sat Jun 28 04:49:42.652661 2014] [:error] [pid 21975] 
[Sat Jun 28 04:52:42.257545 2014] [:error] [pid 22115] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 04:52:42.257610 2014] [:error] [pid 22115]   from django.utils import simplejson
[Sat Jun 28 04:52:42.257618 2014] [:error] [pid 22115] 
[Sat Jun 28 04:52:43.591426 2014] [:error] [pid 22114] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 04:52:43.591478 2014] [:error] [pid 22114]   from django.utils import simplejson
[Sat Jun 28 04:52:43.591483 2014] [:error] [pid 22114] 
[Sat Jun 28 05:04:17.275891 2014] [:error] [pid 22275] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:04:17.275939 2014] [:error] [pid 22275]   from django.utils import simplejson
[Sat Jun 28 05:04:17.275944 2014] [:error] [pid 22275] 
[Sat Jun 28 05:04:18.360065 2014] [:error] [pid 22274] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:04:18.360127 2014] [:error] [pid 22274]   from django.utils import simplejson
[Sat Jun 28 05:04:18.360133 2014] [:error] [pid 22274] 
[Sat Jun 28 05:12:36.481530 2014] [:error] [pid 22425] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:12:36.481586 2014] [:error] [pid 22425]   from django.utils import simplejson
[Sat Jun 28 05:12:36.481592 2014] [:error] [pid 22425] 
[Sat Jun 28 05:12:37.560349 2014] [:error] [pid 22424] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:12:37.560398 2014] [:error] [pid 22424]   from django.utils import simplejson
[Sat Jun 28 05:12:37.560403 2014] [:error] [pid 22424] 
[Sat Jun 28 05:36:17.379697 2014] [:error] [pid 22586] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:36:17.379753 2014] [:error] [pid 22586]   from django.utils import simplejson
[Sat Jun 28 05:36:17.379759 2014] [:error] [pid 22586] 
[Sat Jun 28 05:37:20.785661 2014] [:error] [pid 22720] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:37:20.785727 2014] [:error] [pid 22720]   from django.utils import simplejson
[Sat Jun 28 05:37:20.785736 2014] [:error] [pid 22720] 
[Sat Jun 28 05:37:21.883529 2014] [:error] [pid 22719] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:37:21.883579 2014] [:error] [pid 22719]   from django.utils import simplejson
[Sat Jun 28 05:37:21.883584 2014] [:error] [pid 22719] 
[Sat Jun 28 05:43:06.246225 2014] [:error] [pid 22889] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:43:06.246280 2014] [:error] [pid 22889]   from django.utils import simplejson
[Sat Jun 28 05:43:06.246285 2014] [:error] [pid 22889] 
[Sat Jun 28 05:43:07.547691 2014] [:error] [pid 22888] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:43:07.547740 2014] [:error] [pid 22888]   from django.utils import simplejson
[Sat Jun 28 05:43:07.547746 2014] [:error] [pid 22888] 
[Sat Jun 28 05:47:16.445278 2014] [:error] [pid 23028] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:47:16.445333 2014] [:error] [pid 23028]   from django.utils import simplejson
[Sat Jun 28 05:47:16.445338 2014] [:error] [pid 23028] 
[Sat Jun 28 05:47:17.770422 2014] [:error] [pid 23027] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:47:17.770472 2014] [:error] [pid 23027]   from django.utils import simplejson
[Sat Jun 28 05:47:17.770477 2014] [:error] [pid 23027] 
[Sat Jun 28 05:52:08.889546 2014] [:error] [pid 23167] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:52:08.889601 2014] [:error] [pid 23167]   from django.utils import simplejson
[Sat Jun 28 05:52:08.889606 2014] [:error] [pid 23167] 
[Sat Jun 28 05:52:09.874932 2014] [:error] [pid 23166] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:52:09.874989 2014] [:error] [pid 23166]   from django.utils import simplejson
[Sat Jun 28 05:52:09.874994 2014] [:error] [pid 23166] 
[Sat Jun 28 05:54:11.770652 2014] [:error] [pid 23306] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:54:11.770699 2014] [:error] [pid 23306]   from django.utils import simplejson
[Sat Jun 28 05:54:11.770705 2014] [:error] [pid 23306] 
[Sat Jun 28 05:54:53.590474 2014] [:error] [pid 23440] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:54:53.590532 2014] [:error] [pid 23440]   from django.utils import simplejson
[Sat Jun 28 05:54:53.590538 2014] [:error] [pid 23440] 
[Sat Jun 28 05:54:54.949316 2014] [:error] [pid 23439] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 05:54:54.949366 2014] [:error] [pid 23439]   from django.utils import simplejson
[Sat Jun 28 05:54:54.949372 2014] [:error] [pid 23439] 
[Sat Jun 28 06:01:17.475968 2014] [:error] [pid 23731] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:01:17.476018 2014] [:error] [pid 23731]   from django.utils import simplejson
[Sat Jun 28 06:01:17.476024 2014] [:error] [pid 23731] 
[Sat Jun 28 06:01:18.792724 2014] [:error] [pid 23730] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:01:18.792775 2014] [:error] [pid 23730]   from django.utils import simplejson
[Sat Jun 28 06:01:18.792780 2014] [:error] [pid 23730] 
[Sat Jun 28 06:05:02.650401 2014] [:error] [pid 23870] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:05:02.650452 2014] [:error] [pid 23870]   from django.utils import simplejson
[Sat Jun 28 06:05:02.650458 2014] [:error] [pid 23870] 
[Sat Jun 28 06:05:03.377227 2014] [:error] [pid 23869] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:05:03.377276 2014] [:error] [pid 23869]   from django.utils import simplejson
[Sat Jun 28 06:05:03.377282 2014] [:error] [pid 23869] 
[Sat Jun 28 06:07:21.973350 2014] [:error] [pid 24006] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:07:21.973408 2014] [:error] [pid 24006]   from django.utils import simplejson
[Sat Jun 28 06:07:21.973414 2014] [:error] [pid 24006] 
[Sat Jun 28 06:07:23.160135 2014] [:error] [pid 24005] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:07:23.160183 2014] [:error] [pid 24005]   from django.utils import simplejson
[Sat Jun 28 06:07:23.160188 2014] [:error] [pid 24005] 
[Sat Jun 28 06:09:18.875716 2014] [:error] [pid 24156] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:09:18.875772 2014] [:error] [pid 24156]   from django.utils import simplejson
[Sat Jun 28 06:09:18.875778 2014] [:error] [pid 24156] 
[Sat Jun 28 06:09:20.159196 2014] [:error] [pid 24155] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:09:20.159248 2014] [:error] [pid 24155]   from django.utils import simplejson
[Sat Jun 28 06:09:20.159253 2014] [:error] [pid 24155] 
[Sat Jun 28 02:17:42.591718 2014] [:error] [pid 24298] [remote 187.151.20.205:46573] mod_wsgi (pid=24298): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Sat Jun 28 02:17:42.591797 2014] [:error] [pid 24298] [remote 187.151.20.205:46573] Traceback (most recent call last):
[Sat Jun 28 02:17:42.591837 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]   File "/var/www/djalton/djalton/wsgi.py", line 31, in application
[Sat Jun 28 02:17:42.591915 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]     return _application(environ, start_response)
[Sat Jun 28 02:17:42.591934 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Sat Jun 28 02:17:42.592495 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]     self.load_middleware()
[Sat Jun 28 02:17:42.592515 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Sat Jun 28 02:17:42.592658 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sat Jun 28 02:17:42.592677 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Sat Jun 28 02:17:42.593234 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]     self._setup(name)
[Sat Jun 28 02:17:42.593255 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Sat Jun 28 02:17:42.593282 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]     self._wrapped = Settings(settings_module)
[Sat Jun 28 02:17:42.593295 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
[Sat Jun 28 02:17:42.593315 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sat Jun 28 02:17:42.593328 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
[Sat Jun 28 02:17:42.593386 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]     __import__(name)
[Sat Jun 28 02:17:42.593403 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]   File "/var/www/djalton/djalton/settings.py", line 110, in <module>
[Sat Jun 28 02:17:42.593483 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]     EMAIL_HOST_USER = os.environ['jualjiman@gmail.com']
[Sat Jun 28 02:17:42.593502 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]   File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
[Sat Jun 28 02:17:42.593952 2014] [:error] [pid 24298] [remote 187.151.20.205:46573]     raise KeyError(key)
[Sat Jun 28 02:17:42.593999 2014] [:error] [pid 24298] [remote 187.151.20.205:46573] KeyError: 'jualjiman@gmail.com'
[Sat Jun 28 02:17:45.713311 2014] [:error] [pid 24298] [remote 187.151.20.205:23767] mod_wsgi (pid=24298): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Sat Jun 28 02:17:45.713378 2014] [:error] [pid 24298] [remote 187.151.20.205:23767] Traceback (most recent call last):
[Sat Jun 28 02:17:45.713420 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]   File "/var/www/djalton/djalton/wsgi.py", line 31, in application
[Sat Jun 28 02:17:45.713466 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]     return _application(environ, start_response)
[Sat Jun 28 02:17:45.713488 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Sat Jun 28 02:17:45.713527 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]     self.load_middleware()
[Sat Jun 28 02:17:45.713546 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Sat Jun 28 02:17:45.713620 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sat Jun 28 02:17:45.713660 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Sat Jun 28 02:17:45.713698 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]     self._setup(name)
[Sat Jun 28 02:17:45.713717 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Sat Jun 28 02:17:45.713748 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]     self._wrapped = Settings(settings_module)
[Sat Jun 28 02:17:45.713768 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
[Sat Jun 28 02:17:45.713799 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sat Jun 28 02:17:45.713819 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]   File "/usr/local/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
[Sat Jun 28 02:17:45.713851 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]     __import__(name)
[Sat Jun 28 02:17:45.713988 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]   File "/var/www/djalton/djalton/settings.py", line 110, in <module>
[Sat Jun 28 02:17:45.714027 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]     EMAIL_HOST_USER = os.environ['jualjiman@gmail.com']
[Sat Jun 28 02:17:45.714047 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]   File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
[Sat Jun 28 02:17:45.714080 2014] [:error] [pid 24298] [remote 187.151.20.205:23767]     raise KeyError(key)
[Sat Jun 28 02:17:45.714115 2014] [:error] [pid 24298] [remote 187.151.20.205:23767] KeyError: 'jualjiman@gmail.com'
[Sat Jun 28 06:24:10.478052 2014] [:error] [pid 24453] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:24:10.478098 2014] [:error] [pid 24453]   from django.utils import simplejson
[Sat Jun 28 06:24:10.478104 2014] [:error] [pid 24453] 
[Sat Jun 28 06:24:11.493163 2014] [:error] [pid 24452] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:24:11.493226 2014] [:error] [pid 24452]   from django.utils import simplejson
[Sat Jun 28 06:24:11.493234 2014] [:error] [pid 24452] 
[Sat Jun 28 06:35:53.768824 2014] [:error] [pid 24589] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:35:53.768880 2014] [:error] [pid 24589]   from django.utils import simplejson
[Sat Jun 28 06:35:53.768887 2014] [:error] [pid 24589] 
[Sat Jun 28 06:35:54.872678 2014] [:error] [pid 24590] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 06:35:54.872730 2014] [:error] [pid 24590]   from django.utils import simplejson
[Sat Jun 28 06:35:54.872735 2014] [:error] [pid 24590] 
[Sat Jun 28 16:12:24.257988 2014] [:error] [pid 25684] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:12:24.258044 2014] [:error] [pid 25684]   from django.utils import simplejson
[Sat Jun 28 16:12:24.258049 2014] [:error] [pid 25684] 
[Sat Jun 28 16:12:27.155510 2014] [:error] [pid 25683] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:12:27.155553 2014] [:error] [pid 25683]   from django.utils import simplejson
[Sat Jun 28 16:12:27.155558 2014] [:error] [pid 25683] 
[Sat Jun 28 16:14:36.673705 2014] [:error] [pid 25826] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:14:36.673768 2014] [:error] [pid 25826]   from django.utils import simplejson
[Sat Jun 28 16:14:36.673773 2014] [:error] [pid 25826] 
[Sat Jun 28 16:14:38.156412 2014] [:error] [pid 25825] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:14:38.156455 2014] [:error] [pid 25825]   from django.utils import simplejson
[Sat Jun 28 16:14:38.156461 2014] [:error] [pid 25825] 
[Sat Jun 28 16:20:51.693928 2014] [:error] [pid 26010] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:20:51.693991 2014] [:error] [pid 26010]   from django.utils import simplejson
[Sat Jun 28 16:20:51.693996 2014] [:error] [pid 26010] 
[Sat Jun 28 16:20:54.482649 2014] [:error] [pid 26009] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:20:54.482702 2014] [:error] [pid 26009]   from django.utils import simplejson
[Sat Jun 28 16:20:54.482708 2014] [:error] [pid 26009] 
[Sat Jun 28 16:23:49.189383 2014] [:error] [pid 26177] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:23:49.189444 2014] [:error] [pid 26177]   from django.utils import simplejson
[Sat Jun 28 16:23:49.189456 2014] [:error] [pid 26177] 
[Sat Jun 28 16:23:50.680153 2014] [:error] [pid 26176] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:23:50.680204 2014] [:error] [pid 26176]   from django.utils import simplejson
[Sat Jun 28 16:23:50.680210 2014] [:error] [pid 26176] 
[Sat Jun 28 16:27:36.484101 2014] [:error] [pid 26320] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:27:36.484154 2014] [:error] [pid 26320]   from django.utils import simplejson
[Sat Jun 28 16:27:36.484159 2014] [:error] [pid 26320] 
[Sat Jun 28 16:27:38.553328 2014] [:error] [pid 26319] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:27:38.553374 2014] [:error] [pid 26319]   from django.utils import simplejson
[Sat Jun 28 16:27:38.553379 2014] [:error] [pid 26319] 
[Sat Jun 28 16:30:13.765915 2014] [:error] [pid 26459] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:30:13.765972 2014] [:error] [pid 26459]   from django.utils import simplejson
[Sat Jun 28 16:30:13.765977 2014] [:error] [pid 26459] 
[Sat Jun 28 16:30:15.280909 2014] [:error] [pid 26458] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:30:15.280959 2014] [:error] [pid 26458]   from django.utils import simplejson
[Sat Jun 28 16:30:15.280965 2014] [:error] [pid 26458] 
[Sat Jun 28 16:32:31.552130 2014] [:error] [pid 26701] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:32:31.552186 2014] [:error] [pid 26701]   from django.utils import simplejson
[Sat Jun 28 16:32:31.552192 2014] [:error] [pid 26701] 
[Sat Jun 28 16:32:33.085158 2014] [:error] [pid 26702] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:32:33.085218 2014] [:error] [pid 26702]   from django.utils import simplejson
[Sat Jun 28 16:32:33.085228 2014] [:error] [pid 26702] 
[Sat Jun 28 16:40:40.584698 2014] [:error] [pid 26871] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:40:40.584765 2014] [:error] [pid 26871]   from django.utils import simplejson
[Sat Jun 28 16:40:40.584770 2014] [:error] [pid 26871] 
[Sat Jun 28 16:40:42.251683 2014] [:error] [pid 26870] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:40:42.251731 2014] [:error] [pid 26870]   from django.utils import simplejson
[Sat Jun 28 16:40:42.251736 2014] [:error] [pid 26870] 
[Sat Jun 28 16:45:51.063973 2014] [:error] [pid 27034] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:45:51.064043 2014] [:error] [pid 27034]   from django.utils import simplejson
[Sat Jun 28 16:45:51.064055 2014] [:error] [pid 27034] 
[Sat Jun 28 16:47:41.164389 2014] [:error] [pid 27168] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:47:41.164445 2014] [:error] [pid 27168]   from django.utils import simplejson
[Sat Jun 28 16:47:41.164450 2014] [:error] [pid 27168] 
[Sat Jun 28 16:47:43.576520 2014] [:error] [pid 27167] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Sat Jun 28 16:47:43.576566 2014] [:error] [pid 27167]   from django.utils import simplejson
[Sat Jun 28 16:47:43.576571 2014] [:error] [pid 27167] 
[Mon Jun 30 04:15:32.489431 2014] [:error] [pid 5032] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Mon Jun 30 04:15:32.489483 2014] [:error] [pid 5032]   from django.utils import simplejson
[Mon Jun 30 04:15:32.489489 2014] [:error] [pid 5032] 
[Mon Jun 30 04:30:31.188198 2014] [:error] [pid 5031] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Mon Jun 30 04:30:31.188251 2014] [:error] [pid 5031]   from django.utils import simplejson
[Mon Jun 30 04:30:31.188256 2014] [:error] [pid 5031] 
[Fri Jul 04 03:51:18.487539 2014] [:error] [pid 15755] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jul 04 03:51:18.487592 2014] [:error] [pid 15755]   from django.utils import simplejson
[Fri Jul 04 03:51:18.487598 2014] [:error] [pid 15755] 
[Fri Jul 04 03:51:19.472119 2014] [:error] [pid 15754] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jul 04 03:51:19.472184 2014] [:error] [pid 15754]   from django.utils import simplejson
[Fri Jul 04 03:51:19.472197 2014] [:error] [pid 15754] 
[Fri Jul 04 04:00:35.931499 2014] [:error] [pid 16418] [remote 187.151.7.254:23836] mod_wsgi (pid=16418): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Fri Jul 04 04:00:35.931644 2014] [:error] [pid 16418] [remote 187.151.7.254:23836] IOError: failed to write data
[Fri Jul 04 04:00:36.136315 2014] [:error] [pid 16418] [remote 187.151.7.254:23836] mod_wsgi (pid=16418): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Fri Jul 04 04:00:36.136437 2014] [:error] [pid 16418] [remote 187.151.7.254:23836] IOError: failed to write data
[Fri Jul 04 04:00:37.833822 2014] [:error] [pid 16419] [remote 187.151.7.254:44338] mod_wsgi (pid=16419): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Fri Jul 04 04:00:37.833967 2014] [:error] [pid 16419] [remote 187.151.7.254:44338] IOError: failed to write data
[Fri Jul 04 04:00:38.091006 2014] [:error] [pid 16419] [remote 187.151.7.254:23836] mod_wsgi (pid=16419): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Fri Jul 04 04:00:38.091146 2014] [:error] [pid 16419] [remote 187.151.7.254:23836] IOError: failed to write data
[Fri Jul 04 04:00:38.119944 2014] [:error] [pid 16419] [remote 187.151.7.254:44338] mod_wsgi (pid=16419): Exception occurred processing WSGI script '/var/www/djalton/djalton/wsgi.py'.
[Fri Jul 04 04:00:38.120023 2014] [:error] [pid 16419] [remote 187.151.7.254:44338] IOError: failed to write data
[Fri Jul 04 04:31:12.690431 2014] [:error] [pid 16740] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jul 04 04:31:12.690492 2014] [:error] [pid 16740]   from django.utils import simplejson
[Fri Jul 04 04:31:12.690502 2014] [:error] [pid 16740] 
[Fri Jul 04 04:32:12.470807 2014] [:error] [pid 16739] /usr/local/lib/python2.7/dist-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
[Fri Jul 04 04:32:12.470865 2014] [:error] [pid 16739]   from django.utils import simplejson
[Fri Jul 04 04:32:12.470871 2014] [:error] [pid 16739] 
